packages:
  - packages/**
  - apps/**
catalog:
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
  starknet: ^7.6.2
onlyBuiltDependencies:
  - "@biomejs/biome"
  - better-sqlite3
  - canvas
  - cbor-extract
  - esbuild
  - nx
