name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.0.0

      - name: "Setup npm"
        run: |
          npm set @pixelaw:registry=https://npm.pkg.github.com/pixelaw
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: pnpm i

      - name: Run biome lint
        run: pnpm run lint

      - name: Build packages and examples
        run: pnpm run build --ui stream

